# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='count',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Количество'),
        ),
    ]
