# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171004_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Статус заказа'),
        ),
    ]
