# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20171005_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=6, verbose_name='Итоговая цена за товар'),
            preserve_default=False,
        ),
    ]
