# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=-1, max_length=50, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
